server:
  port: 8090
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  data:
    mongodb:
      database: devicemangerdb
      username: root
      password: secret
      port: 27017
      host: localhost

app:
  system:
    id: device-controller-001
  iam-client:
    organization-id: device-controller
    project-id: device-controller
    base-url: http://127.0.0.1:8080
    polling-interval: 30
    time-unit: SECONDS

logging:
  level:
    root: INFO
    one:
      microproject:
        devicecontroller: DEBUG
