server:
  port: 8090
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 20s
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}

app:
  iam-client:
    organization-id: ${IAM_ORG_ID}
    project-id: ${IAM_PROJECT_ID}
    base-url: ${IAM_URL}
    polling-interval: 30
    time-unit: SECONDS

logging:
  level:
    root: ${LOG_ROOT_LEVEL}
    one:
      microproject:
        devicecontroller: ${LOG_APP_LEVEL}
