version: '3.1'

services:

  iam-service:
    image: jurajveverka/iam-service:2.5.5-RELEASE-amd64
    restart: always
    network_mode: 'host'
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.4.4-bionic
    restart: always
    network_mode: 'host'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret

  device-controller:
    image: device-controller:1.0.0-SNAPSHOT
    build:
      context: ./device-controller
      dockerfile: Dockerfile
    network_mode: 'host'
    ports:
      - 8090:8090
    depends_on:
      - mongo
    environment:
      MONGO_DATABASE: admin
      MONGO_USERNAME: root
      MONGO_PASSWORD: secret
      MONGO_PORT: 27017
      MONGO_HOST: 127.0.0.1
      LOG_ROOT_LEVEL: INFO
      LOG_APP_LEVEL: DEBUG
