# This workflow will build a Java project with Gradle
name: Build and Test

on:
  push:
    branches: [ master, pi4j-v2 ]
  pull_request:
    branches: [ master, pi4j-v2 ]

jobs:
  build-core-java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle --info clean build test

  build-device-controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle --build-file device-controller/build.gradle clean test

