# This workflow will build a Java project with Gradle
name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-core-java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle --info clean build test

  build-core-java11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle --info clean build test

  build-device-controller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Check Java version
        run: java -version
      - name: Check Gradle version
        run: gradle -version
      - name: Run Gradle Build and tests
        run: gradle --build-file device-controller/build.gradle clean test

